name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Copy myalvinpages to gh-pages branch
      run: |
        # Install Git if not available
        sudo apt-get install git
        
        # Configure Git user
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        # Checkout gh-pages branch
        git fetch origin gh-pages
        git checkout gh-pages
        
        # Remove all files from the gh-pages branch (if any)
        rm -rf *
        
        # Copy the contents of myalvinpages folder from main branch
        cp -r myalvinpages/* .
        
        # Add the changes
        git add .
        
        # Commit and push the changes to gh-pages
        git commit -m "Deploy to gh-pages"
        git push origin gh-pages
