name: Update Node Links

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜自动运行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  update-nodes:
    runs-on: ubuntu-latest

    steps:
    # 检出代码库
    - name: Checkout repository
      uses: actions/checkout@v3

    # 获取网页内容并保存为文件，去掉 HTML 标签
    - name: Fetch and Clean Webpage Content
      run: |
        VMESS_URL="https://github.com/Alvin9999/new-pac/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7"
        SS_URL="https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7"
        
        # 获取网页内容，去掉 HTML 标签，并保存为纯文本文件
        curl -s "$VMESS_URL" | sed 's/<[^>]*>//g' > webpage_content.txt
        curl -s "$SS_URL" | sed 's/<[^>]*>//g' > ss_webpage_content.txt
        echo "Webpage content cleaned and saved."

    # 从保存的完整网页内容中提取并更新节点信息
    - name: Fetch and Update Nodes from Content Files
      run: |
        # 提取包含 vmess://、vless://、ss:// 的整行内容
        VMESS_NODES=$(grep -oP '.*vmess://\S+' webpage_content.txt | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s/&amp;/\&/g' | sort -u)
        VLESS_NODES=$(grep -oP '.*vless://\S+' webpage_content.txt | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s/&amp;/\&/g' | sort -u)
        SS_NODES=$(grep -oP '.*ss://\S+' ss_webpage_content.txt | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s/&amp;/\&/g' | sort -u)

        # 保存提取的节点链接到文件
        echo "$VMESS_NODES" > dizhi1.txt
        echo "$VLESS_NODES" > dizhi2.txt
        echo "$SS_NODES" > dizhi3.txt
        echo "Node data saved to files."

    # 检查文件是否发生变化，如果有变化才提交
    - name: Check if files changed
      run: |
        git diff --exit-code dizhi1.txt dizhi2.txt dizhi3.txt ss_webpage_content.txt webpage_content.txt
      continue-on-error: true

    # 提交文件更新（如果文件有变化）
    - name: Commit and Push changes
      run: |
        if [[ $(git diff --exit-code dizhi1.txt dizhi2.txt dizhi3.txt ss_webpage_content.txt webpage_content.txt) ]]; then
          echo "No changes detected. Skipping commit."
        else
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dizhi1.txt dizhi2.txt dizhi3.txt ss_webpage_content.txt webpage_content.txt
          git commit -m "Update nodes data"
          git push
        fi
