name: Update Node Links

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜自动运行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  update-nodes:
    runs-on: ubuntu-latest

    steps:
    # 检出代码库
    - name: Checkout repository
      uses: actions/checkout@v3

    # 获取 v2ray 和 vless 节点链接并更新 dizhi1.txt
    - name: Fetch and Update v2ray and vless Nodes
      run: |
        # 安装依赖
        sudo apt-get update
        sudo apt-get install -y curl jq

        # 从v2ray免费账号网页抓取数据
        VMESS_URL="https://github.com/Alvin9999/new-pac/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7"
        VLESS_URL="https://github.com/Alvin9999/new-pac/wiki/vless%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7"

        # 抓取 vmess 节点
        VMESS_NODES=$(curl -s "$VMESS_URL" | grep -oP 'vmess://[^"]+' | sed 's/<[^>]*>//g')

        # 抓取 vless 节点（包括查询参数和 URL 编码部分）
        VLESS_NODES=$(curl -s "$VLESS_URL" | grep -oP 'vless://[^"]+' | sed 's/<[^>]*>//g')

        # 合并 vmess 和 vless 节点，去重
        ALL_NODES=$(echo -e "$VMESS_NODES\n$VLESS_NODES" | sort -u)

        # 检查文件是否需要更新
        if [ -f "dizhi1.txt" ]; then
          # 使用 cmp 比较文件内容
          if cmp -s "dizhi1.txt" <(echo "$ALL_NODES"); then
            echo "v2ray and vless nodes have not changed, skipping update."
            exit 0
          fi
        fi

        # 更新 dizhi1.txt 文件
        echo "$ALL_NODES" > dizhi1.txt
        echo "v2ray and vless nodes updated successfully."

    # 获取 ss 节点链接并更新 dizhi2.txt
    - name: Fetch and Update ss Nodes
      run: |
        # 从ss免费账号网页抓取数据
        SS_URL="https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7"
        SS_NODES=$(curl -s "$SS_URL" | grep -oP 'ss://[^"]+' | sed 's/<[^>]*>//g' | sort -u)

        # 检查文件是否需要更新
        if [ -f "dizhi2.txt" ]; then
          # 使用 cmp 比较文件内容
          if cmp -s "dizhi2.txt" <(echo "$SS_NODES"); then
            echo "ss nodes have not changed, skipping update."
            exit 0
          fi
        fi

        # 更新 dizhi2.txt 文件
        echo "$SS_NODES" > dizhi2.txt
        echo "ss nodes updated successfully."

    # 提交文件更新
    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add dizhi1.txt dizhi2.txt
        git commit -m "Update nodes data"
        git push
